parameter_defaults:
  ControllerCount: 1
  OvercloudControllerFlavor: control

  ComputeHCICount: 3
  OvercloudComputeHCIFlavor: osdcompute

  TimeZone: 'Japan'
  NtpServer: '133.243.238.163'

  NeutronNetworkType: 'vxlan,vlan'
  NeutronTunnelTypes: 'vxlan'


